### PR TITLE
Fixed service name delete#paymentMethod to delete#PaymentMethod

### PR DESCRIPTION
**Pull request by hellozhangwei**

### CODE REVIEW

**Comment by jonesde** [comment]
It looks like these commits also fix a pagination issue, is that correct?

One odd thing: in the AUTHORS file there is one line added for "fraybaotalora" but I don't see any commits from that account included. It is okay to add them if commits when through another account, but two lines are needed in the AUTHORS file (one for the CC0 license, one for the patent disclaimer).

**Comment by hellozhangwei** [comment]
Yes, it fixed a paginatio issue. I've fixed the AUTHORS file.

**Comment by jonesde** [comment]
In the AUTHORS file there is only one line added, in the Grant of Patent License section, another line for you is also needed in the section above for the CC0 copyright disclaimer/license. Thanks for your contributions on PopRestStore, it hasn't seen a lot of effort since the early development.

**Comment by hellozhangwei** [comment]
Added another line section CC0 copyright

**Pull request merged**
